### ISSUE TITLE
User command fails during provisioning when host user ID is not 1000

### ISSUE THREAD

**Issue by francoisbruneau** [liip/drifter#246] opened 2018-12-06 16:30 UTC
```
RUNNING HANDLER [nodejs : install package.json] ********************************
fatal: [default]: FAILED! => {"changed": false, "cmd": "/usr/bin/npm install", "failed": true, "msg": "npm WARN checkPermissions Missing write access to /vagrant\nnpm
```

This happens when the host user ID is not the default one (1000), i.e. when multiple user accounts have been setup on the host machine.

**Workaround** 
Assuming host user ID is 1001:
``` 
$ vagrant halt
$ sudo su
$ cd /var/lib/lxc/CONTAINER_NAME
$ chroot rootfs

/# usermod -u 1001 vagrant
/# groupmod -g 1001 vagrant
/# exit

$ cd PROJECT_DIRECTORY
$ vagrant up --provision 
``` 

**Drifter version:**  stretch-php7 https://github.com/liip/drifter/commit/88ac0c7df1ba97114947678906faccb2b6622ef5
**Vagrant version:** 2.2.2
**OS and version:** Ubuntu 18.10

**Additional information:**

* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens to my colleagues as well: Yes

**Comment by LeBenLeBen** [comment] 2019-01-01 14:13
Duplicate of #107

**Closed by LeBenLeBen** 2019-01-01 14:13 UTC
Labels: area: core
